package com.financeos.gmail.domain;

public enum GmailProcessedStatus {
    DISCOVERED,
    PROCESSING,
    CREATED,
    RECONCILED,
    SKIPPED_NOT_TRANSACTION,
    SKIPPED_BEFORE_WATERMARK,
    SKIPPED_SENDER_DISABLED,
    SKIPPED_DUPLICATE,
    SKIPPED_MESSAGE_GONE,
    UNRESOLVED_ACCOUNT,
    ACCOUNT_NOT_OPTED_IN,
    FAILED_RETRYABLE,
    FAILED_PERMANENT
}
