package com.financeos.core;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.web.servlet.MockMvc;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "springdoc.api-docs.enabled=true",
        "spring.session.store-type=none"
})
class OpenApiExportTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    void exportApiSpecYaml() throws Exception {
        byte[] yamlBytes = mockMvc.perform(get("/v3/api-docs.yaml"))
                .andExpect(status().isOk())
                .andReturn()
                .getResponse()
                .getContentAsByteArray();

        String yamlContent = new String(yamlBytes, StandardCharsets.UTF_8);
        String formatted = "# GENERATED by scripts/export-openapi.sh — do not edit by hand\n" + yamlContent;

        File specFile = new File("api-spec.yaml");
        Files.writeString(specFile.toPath(), formatted, StandardCharsets.UTF_8);
        System.out.println("Exported OpenAPI spec to " + specFile.getAbsolutePath() + " (" + yamlBytes.length + " bytes)");
    }
}
