#!/usr/bin/env bash
set -euo pipefail

PORT="${SERVER_PORT:-6969}"
HOST="http://localhost:${PORT}"
DOCS_URL="${HOST}/v3/api-docs.yaml"
OUTPUT_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/api-spec.yaml"

echo "Checking if FinanceOS server is reachable at ${HOST}..."
if ! curl -s -f -o /dev/null "${HOST}/actuator/health" 2>/dev/null; then
    echo "ERROR: Server is not reachable at ${HOST}. Please start the backend with OPENAPI_DOCS_ENABLED=true."
    exit 1
fi

echo "Fetching OpenAPI spec from ${DOCS_URL}..."
TMP_FILE="$(mktemp)"

if ! curl -s -f -o "${TMP_FILE}" "${DOCS_URL}"; then
    echo "ERROR: Failed to fetch OpenAPI documentation from ${DOCS_URL}."
    echo "Ensure OPENAPI_DOCS_ENABLED=true is set in your environment / application.yml."
    rm -f "${TMP_FILE}"
    exit 1
fi

# Add top comment banner
{
    echo "# GENERATED by scripts/export-openapi.sh — do not edit by hand"
    cat "${TMP_FILE}"
} > "${OUTPUT_FILE}"

rm -f "${TMP_FILE}"

# Count paths
PATH_COUNT=$(grep -E '^[[:space:]]{2}/api/' "${OUTPUT_FILE}" | wc -l | tr -d ' ')
if [ -z "${PATH_COUNT}" ] || [ "${PATH_COUNT}" -eq 0 ]; then
    # Fallback path count using awk or grep
    PATH_COUNT=$(grep -E '^  /' "${OUTPUT_FILE}" | wc -l | tr -d ' ')
fi

echo "Successfully exported OpenAPI spec to ${OUTPUT_FILE}"
echo "Total paths exported: ${PATH_COUNT}"
