-- Refactor transaction_categories to support Join Entity model with surrogate ID
-- This resolves ORA-12860 by providing explicit control over row locking

-- 1. Add surrogate ID column with auto-generation
ALTER TABLE transaction_categories ADD id NUMBER GENERATED BY DEFAULT AS IDENTITY;

-- 2. Refactor constraints
ALTER TABLE transaction_categories DROP PRIMARY KEY;
ALTER TABLE transaction_categories ADD PRIMARY KEY (id);

-- 3. Ensure uniqueness of the relationship (logical primary key)
ALTER TABLE transaction_categories ADD CONSTRAINT uc_transaction_category UNIQUE (transaction_id, category_id);

-- 4. Clean up potentially redundant indexes
-- Note: UNIQUE constraint already creates an index on (transaction_id, category_id)
-- We can drop the single-column index on transaction_id if it exists to reduce overhead
-- idx_tc_transaction_id was created in V4
DROP INDEX idx_tc_transaction_id;
